from spectra._rust import __version__

# Waveforms
from spectra.waveforms import (
    AMDSB,
    AMDSB_SC,
    AMLSB,
    AMUSB,
    ASK4,
    ASK8,
    ASK16,
    ASK32,
    ASK64,
    BarkerCode,
    BPSK,
    ChirpSS,
    CostasCode,
    DSSS_BPSK,
    FM,
    FrankCode,
    FSK,
    FSK4,
    FSK8,
    FSK16,
    GFSK,
    GFSK4,
    GFSK8,
    GFSK16,
    GMSK,
    GMSK4,
    GMSK8,
    LFM,
    MSK,
    MSK4,
    MSK8,
    Noise,
    OFDM,
    OFDM72,
    OFDM128,
    OFDM180,
    OFDM256,
    OFDM300,
    OFDM512,
    OFDM600,
    OFDM900,
    OFDM1200,
    OFDM2048,
    OOK,
    SCFDMA,
    P1Code,
    P2Code,
    P3Code,
    P4Code,
    PSK8,
    PSK16,
    PSK32,
    PSK64,
    QAM16,
    QAM32,
    QAM64,
    QAM128,
    QAM256,
    QAM512,
    QAM1024,
    QPSK,
    Tone,
    ZadoffChu,
)

# Scene composition
from spectra.scene import Composer, SceneConfig, SignalDescription, STFTParams, to_coco

# Impairments
from spectra.impairments import (
    AdjacentChannelInterference,
    AWGN,
    ColoredNoise,
    Compose,
    DCOffset,
    FrequencyDrift,
    FrequencyOffset,
    IntermodulationProducts,
    IQImbalance,
    PassbandRipple,
    PhaseNoise,
    PhaseOffset,
    Quantization,
    RayleighFading,
    RicianFading,
    SampleRateOffset,
    SpectralInversion,
    TDLChannel,
    MIMOChannel,
    exponential_correlation,
    kronecker_correlation,
    steering_vector,
    RappPA,
    SalehPA,
    FractionalDelay,
    SamplingJitter,
)

# Curriculum
from spectra.curriculum import CurriculumSchedule

# Streaming
from spectra.streaming import StreamingDataLoader

# Benchmarks
from spectra.benchmarks import (
    load_benchmark,
    load_snr_sweep,
    load_channel_benchmark,
    evaluate_snr_sweep,
    evaluate_channel_conditions,
)

# Datasets
from spectra.datasets import (
    balanced_sampler,
    collate_fn,
    CutMixDataset,
    CyclostationaryDataset,
    DatasetMetadata,
    ManifestDataset,
    MixUpDataset,
    NarrowbandDataset,
    NarrowbandMetadata,
    SignalFolderDataset,
    SNRSweepDataset,
    WidebandDataset,
    WidebandMetadata,
)

# Transforms
from spectra.transforms import (
    AGC,
    AddSlope,
    AmbiguityFunction,
    BoxesNormalize,
    CAF,
    CWD,
    ChannelSwap,
    ClassIndex,
    ComplexTo2D,
    Cumulants,
    CutMix,
    CutOut,
    EnergyDetector,
    InstantaneousFrequency,
    FAMILY_MAP,
    FamilyIndex,
    FamilyName,
    MixUp,
    Normalize,
    PSD,
    SpectrogramNormalize,
    PatchShuffle,
    RandomDropSamples,
    RandomMagRescale,
    ReassignedGabor,
    SCD,
    SCF,
    Spectrogram,
    STFT,
    TargetTransform,
    TimeReversal,
    WVD,
    YOLOLabel,
)

# DSP Utilities
from spectra.utils import (
    bandwidth_from_bounds,
    center_freq_from_bounds,
    compute_spectrogram,
    convolve,
    frequency_shift,
    gaussian_taps,
    low_pass,
    multistage_resampler,
    noise_generator,
    polyphase_decimator,
    polyphase_interpolator,
    srrc_taps,
    upsample,
)

# Models
from spectra.models import CNNAMC, ResNetAMC

# Metrics
from spectra.metrics import accuracy, classification_report, confusion_matrix, per_snr_accuracy

# Classifiers
from spectra.classifiers import CyclostationaryAMC

# Writer
from spectra.utils.writer import DatasetWriter

# File I/O
from spectra.utils.file_handlers.sigmf_writer import SigMFWriter
from spectra.utils.file_handlers.base_writer import FileWriter
from spectra.utils.file_handlers.dataset_export import export_dataset_to_folder
from spectra.utils.file_handlers.numpy_writer import NumpyWriter
from spectra.utils.file_handlers.raw_writer import RawIQWriter
from spectra.utils.file_handlers.sqlite_writer import SQLiteWriter
from spectra.utils.file_handlers.sqlite_reader import SQLiteReader

# Optional File I/O (h5py)
try:
    from spectra.utils.file_handlers.hdf5_writer import HDF5Writer
except ImportError:
    pass

__all__ = [
    "__version__",
    # Waveforms
    "AMDSB",
    "AMDSB_SC",
    "AMLSB",
    "AMUSB",
    "ASK4",
    "ASK8",
    "ASK16",
    "ASK32",
    "ASK64",
    "BarkerCode",
    "BPSK",
    "ChirpSS",
    "CostasCode",
    "DSSS_BPSK",
    "FM",
    "FrankCode",
    "FSK",
    "FSK4",
    "FSK8",
    "FSK16",
    "GFSK",
    "GFSK4",
    "GFSK8",
    "GFSK16",
    "GMSK",
    "GMSK4",
    "GMSK8",
    "LFM",
    "MSK",
    "MSK4",
    "MSK8",
    "Noise",
    "OFDM",
    "OFDM72",
    "OFDM128",
    "OFDM180",
    "OFDM256",
    "OFDM300",
    "OFDM512",
    "OFDM600",
    "OFDM900",
    "OFDM1200",
    "OFDM2048",
    "OOK",
    "SCFDMA",
    "P1Code",
    "P2Code",
    "P3Code",
    "P4Code",
    "PSK8",
    "PSK16",
    "PSK32",
    "PSK64",
    "QAM16",
    "QAM32",
    "QAM64",
    "QAM128",
    "QAM256",
    "QAM512",
    "QAM1024",
    "QPSK",
    "Tone",
    "ZadoffChu",
    # Scene
    "Composer",
    "SceneConfig",
    "SignalDescription",
    "STFTParams",
    "to_coco",
    # Impairments
    "AdjacentChannelInterference",
    "AWGN",
    "ColoredNoise",
    "Compose",
    "DCOffset",
    "FrequencyDrift",
    "FrequencyOffset",
    "IntermodulationProducts",
    "IQImbalance",
    "PassbandRipple",
    "PhaseNoise",
    "PhaseOffset",
    "Quantization",
    "RayleighFading",
    "RicianFading",
    "SampleRateOffset",
    "SpectralInversion",
    "TDLChannel",
    "MIMOChannel",
    "exponential_correlation",
    "kronecker_correlation",
    "steering_vector",
    "RappPA",
    "SalehPA",
    "FractionalDelay",
    "SamplingJitter",
    # Curriculum
    "CurriculumSchedule",
    # Streaming
    "StreamingDataLoader",
    # Benchmarks
    "load_benchmark",
    "load_snr_sweep",
    "load_channel_benchmark",
    "evaluate_snr_sweep",
    "evaluate_channel_conditions",
    # Datasets
    "balanced_sampler",
    "collate_fn",
    "CutMixDataset",
    "CyclostationaryDataset",
    "DatasetMetadata",
    "ManifestDataset",
    "MixUpDataset",
    "NarrowbandDataset",
    "NarrowbandMetadata",
    "SignalFolderDataset",
    "SNRSweepDataset",
    "WidebandDataset",
    "WidebandMetadata",
    # Transforms
    "AGC",
    "AddSlope",
    "AmbiguityFunction",
    "BoxesNormalize",
    "CAF",
    "ChannelSwap",
    "ClassIndex",
    "ComplexTo2D",
    "Cumulants",
    "CutMix",
    "CutOut",
    "EnergyDetector",
    "FAMILY_MAP",
    "FamilyIndex",
    "FamilyName",
    "MixUp",
    "Normalize",
    "PSD",
    "SpectrogramNormalize",
    "PatchShuffle",
    "RandomDropSamples",
    "RandomMagRescale",
    "SCD",
    "SCF",
    "Spectrogram",
    "STFT",
    "TargetTransform",
    "TimeReversal",
    "CWD",
    "WVD",
    "YOLOLabel",
    # DSP Utils
    "bandwidth_from_bounds",
    "center_freq_from_bounds",
    "compute_spectrogram",
    "convolve",
    "frequency_shift",
    "gaussian_taps",
    "low_pass",
    "multistage_resampler",
    "noise_generator",
    "polyphase_decimator",
    "polyphase_interpolator",
    "srrc_taps",
    "upsample",
    # Models
    "CNNAMC",
    "ResNetAMC",
    # Metrics
    "accuracy",
    "classification_report",
    "confusion_matrix",
    "per_snr_accuracy",
    # Classifiers
    "CyclostationaryAMC",
    # Writer
    "DatasetWriter",
    # File I/O
    "FileWriter",
    "export_dataset_to_folder",
    "SigMFWriter",
    "NumpyWriter",
    "RawIQWriter",
    "SQLiteWriter",
    "SQLiteReader",
]
